amazon-inspector:
    IN-MAL-: IN-MAL-2025-150037.json
kam193:
    pypi/packages/malicious/osv/: 43a247ac6b3c8f93eedcc2868cfcc766e26237bf
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 5b9831ad8622f96270c38e41db314115930b8bb5
ossf-package-analysis:
    confident/: confident/20260117/153045-npm-admin10001-1.0.173.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
