amazon-inspector:
    IN-MAL-: IN-MAL-2025-150037.json
kam193:
    pypi/packages/malicious/osv/: 29bb220426c05f4eece3f107a6bfbcf7fe6f8ece
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 52a1823ab3aa24e01bc8d287f61a1f91e3056ba9
ossf-package-analysis:
    confident/: confident/20260117/153045-npm-admin10001-1.0.173.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
