amazon-inspector:
    IN-MAL-: IN-MAL-2025-149364.json
kam193:
    pypi/packages/malicious/osv/: 4b03dbb683f9132277dd6ca7bc4465fc5247aa52
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 43d4ede7946edae867304b34218023c35384bd05
ossf-package-analysis:
    confident/: confident/20251217/192555-npm-jsondatatoruby-1.999.10.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
