amazon-inspector:
    IN-MAL-: IN-MAL-2025-149292.json
kam193:
    pypi/packages/malicious/osv/: 6089c8f716c6f84ba2dbec96f5264695a78e4a99
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 55e61006a36c4dc9ecee9c3cbe74f03e64909e2e
ossf-package-analysis:
    confident/: confident/20251210/165818-npm-@cheqplease/structured-logger-9.3.2.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
