amazon-inspector:
    IN-MAL-: IN-MAL-2025-149615.json
kam193:
    pypi/packages/malicious/osv/: f54aebceeab2be88139c1cd48bf03602eb416411
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 0e4aa0a3163aaa16aae4fe83a1ef458732b3f85c
ossf-package-analysis:
    confident/: confident/20251229/074542-npm-crypto-trade-analyzer-2.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
