amazon-inspector:
    IN-MAL-: IN-MAL-2026-000234.json
kam193:
    pypi/packages/malicious/osv/: 8ea651becbd8a2327694010b197fcbf64cdc3c11
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 577fec2ab04bcf99bef0000b0680acfbb91598de
ossf-package-analysis:
    confident/: confident/20260227/090504-npm-foundry-toolkit-1.0.2.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
