amazon-inspector:
    IN-MAL-: IN-MAL-2026-000234.json
kam193:
    pypi/packages/malicious/osv/: effa3658981155e4ea5b9ca93472785b4c7d4fef
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 77a3f9c07a02ab60bbfd73bec60e793330b63c67
ossf-package-analysis:
    confident/: confident/20260227/122624-npm-@zinley/orion-1.2.32.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
