amazon-inspector:
    IN-MAL-: IN-MAL-2025-000286.json
ossf-package-analysis:
    confident/: confident/20251103/102332-npm-ethers-5-5.0.9.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
