amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: e874624a27e28f0096aff4e6f6b88d2e235624b9
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: c3468e39b6e705660f2c7c7152a1f73970369222
ossf-package-analysis:
    confident/: confident/20260126/100104-npm-rank4222wun-1.0.80.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
