amazon-inspector:
    IN-MAL-: IN-MAL-2025-149197.json
kam193:
    pypi/packages/malicious/osv/: 0f72d183a027614a7419c27a4bd03b2107d7554e
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: dc9d9fcb20e207bc964b626668f9b274514b319c
ossf-package-analysis:
    confident/: confident/20251209/135736-npm-libxmljs2qwerty-0.30.30.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
