amazon-inspector:
    IN-MAL-: IN-MAL-2025-148218.json
ossf-package-analysis:
    confident/: confident/20251124/033519-npm-cbre-flow-common-99.6.0.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
