amazon-inspector:
    IN-MAL-: IN-MAL-2025-149507.json
kam193:
    pypi/packages/malicious/osv/: 650b22c2a97143b83c9fd64203e65b06a2f229b3
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 43d4ede7946edae867304b34218023c35384bd05
ossf-package-analysis:
    confident/: confident/20251220/082034-npm-escaux-scrumboard-api-999.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
