amazon-inspector:
    IN-MAL-: IN-MAL-2025-147588.json
ossf-package-analysis:
    confident/: confident/20251122/095850-npm-airbnb-story-constants-91.3.0.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
