amazon-inspector:
    IN-MAL-: IN-MAL-2025-149615.json
kam193:
    pypi/packages/malicious/osv/: 11e758bf75af3dc3aaf3d724c71689d0097dc7d4
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: cd79bbe3e3086e9e01c820cccfb5ea0906a8d2c2
ossf-package-analysis:
    confident/: confident/20251222/131106-npm-commander-stable-15.100.101.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
