amazon-inspector:
    IN-MAL-: IN-MAL-2025-149197.json
kam193:
    pypi/packages/malicious/osv/: 54b1d4bae4caec685329cf8d4e698fb8f87b0766
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: 988189cec0db8c5e4ee0fa428c7722a5e4e547fb
ossf-package-analysis:
    confident/: confident/20251210/130726-npm-mws-common-ui-5.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
