amazon-inspector:
    IN-MAL-: IN-MAL-2026-000110.json
kam193:
    pypi/packages/malicious/osv/: 9b939171814527cc0b4636bd835f1ec0925beb37
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 638bcd1641f7c4c566ae700f2eb70ac5d11d0bc6
ossf-package-analysis:
    confident/: confident/20260205/183626-npm-xpack-per-user-1.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
