amazon-inspector:
    IN-MAL-: IN-MAL-2025-149892.json
kam193:
    pypi/packages/malicious/osv/: f4b964bc0742c85b5febcc799ca5d9ab9d43512f
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 6a2786f0ddb5020efeca965206d6225583dcf691
ossf-package-analysis:
    confident/: confident/20260107/134541-npm-@bingads-webui-component-legacy/storage-99.9.9.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
