amazon-inspector:
    IN-MAL-: IN-MAL-2025-149615.json
kam193:
    pypi/packages/malicious/osv/: 0da3c0c824987eae85e61e74bc4b995bb4d228cc
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: d4b1ef822f40a17e7fe3f05a2a7ee9d41d2cf9d1
ossf-package-analysis:
    confident/: confident/20251227/202029-npm-eslint-config-sdk-101.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
