amazon-inspector:
    IN-MAL-: IN-MAL-2025-147902.json
ossf-package-analysis:
    confident/: confident/20251122/124734-npm-doordash-ui-95.6.0.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
