amazon-inspector:
    IN-MAL-: IN-MAL-2025-150300.json
kam193:
    pypi/packages/malicious/osv/: a74970dd57bd4167b7030745016ca8934dc00fb5
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: e46a0c5acb19e608afe38dd482f68551786c3690
ossf-package-analysis:
    confident/: confident/20260131/165854-npm-c11dff444-1.0.3.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
