amazon-inspector:
    IN-MAL-: IN-MAL-2025-150307.json
kam193:
    pypi/packages/malicious/osv/: 33f3bc74f604d492545b6594c5421647aa06fb75
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: c3dbadac25fd1d67e29d2909498369a7f7f56041
ossf-package-analysis:
    confident/: confident/20260202/123755-pypi-theanswre-0.2.3.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
