amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: 4d664cc77bfb04251e359802fcb50f0e5791c157
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 12cc7260a54fe7b17593370680539c8e1f865d27
ossf-package-analysis:
    confident/: confident/20260206/123053-npm-breadcrumb-service-999.9.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
