amazon-inspector:
    IN-MAL-: IN-MAL-2025-150307.json
kam193:
    pypi/packages/malicious/osv/: 3ff61607ba12dac06d4ed0995543b30dac91c7b4
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 3c38e3468151fcbdc0a53807c9cdd587d3dfc498
ossf-package-analysis:
    confident/: confident/20260202/123756-pypi-theanswre-0.2.4.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
