amazon-inspector:
    IN-MAL-: IN-MAL-2025-000283.json
ossf-package-analysis:
    confident/: confident/20251102/232056-pypi-python-requirements-inspector-999.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
