amazon-inspector:
    IN-MAL-: IN-MAL-2025-149364.json
kam193:
    pypi/packages/malicious/osv/: b195d7e42ad8f286e3539cc2b79386782bf954e9
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 18274efc42ff85569015e21fac2b40027370749e
ossf-package-analysis:
    confident/: confident/20251212/115141-npm-mui-wrapper-icons-99.99.1.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
