amazon-inspector:
    IN-MAL-: IN-MAL-2026-000234.json
kam193:
    pypi/packages/malicious/osv/: ed2336b8dfca7f9ba52d2c7f13250e0e993588db
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: e868d3594179d4718f6e996f4a749d1deb8469e0
ossf-package-analysis:
    confident/: confident/20260227/194911-npm-@zinley/orion-1.2.39.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
