amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: 749bcc53cadfb1dd5b9c8ec6c17d427d2dac1cca
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: e7ab9e70da9ed819c43c1b2a946cce266c965749
ossf-package-analysis:
    confident/: confident/20260129/155544-npm-dhgshop-9.0.10.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
