amazon-inspector:
    IN-MAL-: IN-MAL-2025-147588.json
ossf-package-analysis:
    confident/: confident/20251117/220040-npm-transparent-example-request99-1.0.6.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
