amazon-inspector:
    IN-MAL-: IN-MAL-2025-150307.json
kam193:
    pypi/packages/malicious/osv/: 8bee47768ae96e835bb93da762cb07e301973c5f
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: fe1219ff7f76a037414d29e3d42d0eb5839d208a
ossf-package-analysis:
    confident/: confident/20260131/165854-npm-c11dff444-1.0.3.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
