amazon-inspector:
    IN-MAL-: IN-MAL-2025-149892.json
kam193:
    pypi/packages/malicious/osv/: 1e0210f73fd64da221e0cd763c5bc7b32128b44d
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 309650a37e3217312efe2f0e725e374602bc9b81
ossf-package-analysis:
    confident/: confident/20260113/165032-npm-admin1001-4.0.5.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
