amazon-inspector:
    IN-MAL-: IN-MAL-2025-147588.json
ossf-package-analysis:
    confident/: confident/20251119/032512-npm-node-calculator-b0e4-2.1.3.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
