amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: 9ddbaf42e9faeede26ee14af322379bbb288b706
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 6b2a9fd4f570f82abc55d26dce3aa73bb089ec02
ossf-package-analysis:
    confident/: confident/20260206/123053-npm-breadcrumb-service-999.9.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
