amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: e874624a27e28f0096aff4e6f6b88d2e235624b9
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: c265ebc3439a4e8dd954dca7f9517fa161bf7712
ossf-package-analysis:
    confident/: confident/20260126/071051-npm-rank4222wun-1.0.68.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
