amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: 81d7ac13056b545ada8c30135e0b46bd7b965e49
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 36ae0ebfa2c9a0b29ee150da9ff334e2735cbf56
ossf-package-analysis:
    confident/: confident/20260206/040715-npm-@sporting-life/sportinglife-be-386.3.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
