amazon-inspector:
    IN-MAL-: IN-MAL-2026-000234.json
kam193:
    pypi/packages/malicious/osv/: 9cb649176702ab7b8856fdbfc5069df3adcd48df
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 6666804a51137cbc31a62acce589e6e68ce5ed9d
ossf-package-analysis:
    confident/: confident/20260223/133243-npm-vl-ui-checkbox-10.1.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
