amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: 4257045917daf40d67b63d204eb8accaa0b7fdbe
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: aae00f8364e4c5aca46203c4396a7c9508cdb97c
ossf-package-analysis:
    confident/: confident/20260212/221952-npm-@depro0x/despicable-me-6.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
