amazon-inspector:
    IN-MAL-: IN-MAL-2025-150180.json
kam193:
    pypi/packages/malicious/osv/: 91b86e357701147f055596ef328561e6c5fd9322
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 5b9831ad8622f96270c38e41db314115930b8bb5
ossf-package-analysis:
    confident/: confident/20260123/111607-npm-rank4222wun-1.0.15.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
