amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: ec55b5ed0964dd6c60c759271704e15e75272f39
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: c265ebc3439a4e8dd954dca7f9517fa161bf7712
ossf-package-analysis:
    confident/: confident/20260124/090332-npm-rank4222wun-1.0.64.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
