amazon-inspector:
    IN-MAL-: IN-MAL-2025-150037.json
kam193:
    pypi/packages/malicious/osv/: f959f7759af02cd703914464f0724dac6165fe9c
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 5b9831ad8622f96270c38e41db314115930b8bb5
ossf-package-analysis:
    confident/: confident/20260122/122233-npm-un112-1.0.24.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
