amazon-inspector:
    IN-MAL-: IN-MAL-2025-149892.json
kam193:
    pypi/packages/malicious/osv/: e9f43b3e084984cf12198b2b49f4fab94d19da46
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 6a2786f0ddb5020efeca965206d6225583dcf691
ossf-package-analysis:
    confident/: confident/20260106/044527-npm-redis-request-parser-1.2.6.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
