amazon-inspector:
    IN-MAL-: IN-MAL-2025-149017.json
kam193:
    pypi/packages/malicious/osv/: ee68728356184b7f805c2ce175332a80d530fb3f
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
ossf-package-analysis:
    confident/: confident/20251203/142548-npm-elf-stats-frosty-candy-393-1.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
