amazon-inspector:
    IN-MAL-: IN-MAL-2025-149134.json
kam193:
    pypi/packages/malicious/osv/: ee68728356184b7f805c2ce175332a80d530fb3f
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: f80fe845b7ab1a50aa66752a81ecda2026346121
ossf-package-analysis:
    confident/: confident/20251204/103946-npm-elf-stats-bright-cushion-246-5.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
