amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: 4d931d35e8d6044590ee56e84a44793c2716e784
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 8a1644036d004807326b01bee2c8c9b43a050440
ossf-package-analysis:
    confident/: confident/20260212/210406-npm-@depro0x/despicable-me-14.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
