amazon-inspector:
    IN-MAL-: IN-MAL-2025-049959.json
ossf-package-analysis:
    confident/: confident/20251109/045406-npm-karemv1-1.0.8.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
