amazon-inspector:
    IN-MAL-: IN-MAL-2025-148218.json
ossf-package-analysis:
    confident/: confident/20251129/175032-npm-liblynxtextra.so-7.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
