amazon-inspector:
    IN-MAL-: IN-MAL-2025-149777.json
kam193:
    pypi/packages/malicious/osv/: 7394ce931f79a3218f597efdce9884a302e8e31a
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 3bcc0f0b7fc0398daa8632fa940bd3ed781966ce
ossf-package-analysis:
    confident/: confident/20251229/150048-npm-intl-tel-input-utils-99.99.99.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
