amazon-inspector:
    IN-MAL-: IN-MAL-2025-148218.json
ossf-package-analysis:
    confident/: confident/20251128/152916-npm-bitcoin-main-lib-7.1.2.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
