amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: e3b231eb235fa56c0380f315a3e0311f5bd20421
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: e3b231eb235fa56c0380f315a3e0311f5bd20421
ossf-package-analysis:
    confident/: confident/20260130/153112-npm-euskalplantxa-5.8.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
