amazon-inspector:
    IN-MAL-: IN-MAL-2025-149197.json
kam193:
    pypi/packages/malicious/osv/: e1c1e94f18fb24245c7a83a287db3d1544f4592a
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: 0fb102cb4ae4642872aa4cfd6a8b675a7ff1ae25
ossf-package-analysis:
    confident/: confident/20251209/092541-pypi-do-not-install-this-package-001-0.1.3.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
