amazon-inspector:
    IN-MAL-: IN-MAL-2025-149262.json
kam193:
    pypi/packages/malicious/osv/: 4a2d4159ae3446787ebe47d10d9c437ebf518395
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: 780b5dc800cca232f3adedb56587572e82d50ccc
ossf-package-analysis:
    confident/: confident/20251210/165818-npm-@cheqplease/structured-logger-9.3.2.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
