amazon-inspector:
    IN-MAL-: IN-MAL-2025-149892.json
kam193:
    pypi/packages/malicious/osv/: c86e2d4fd31e95839e74e1eb2f52bffda62f8691
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: d60a9797bc6456a65a5ce86d3507af56a64e10e8
ossf-package-analysis:
    confident/: confident/20260115/095056-npm-admin1001-4.4.34.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
