amazon-inspector:
    IN-MAL-: IN-MAL-2025-149364.json
kam193:
    pypi/packages/malicious/osv/: d6ef15cf9a7743d32d41d9482386f645c7cad985
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 43d4ede7946edae867304b34218023c35384bd05
ossf-package-analysis:
    confident/: confident/20251218/111623-npm-sarumaan_a-1.1.1.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
