amazon-inspector:
    IN-MAL-: IN-MAL-2025-149777.json
kam193:
    pypi/packages/malicious/osv/: 2f76190969144ac22ea3d95d99e1f58cba897dea
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 84d727fb59571cac8ef8d3292be4a618ce3c925f
ossf-package-analysis:
    confident/: confident/20251229/160049-npm-kcheck-8.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
