amazon-inspector:
    IN-MAL-: IN-MAL-2026-000234.json
kam193:
    pypi/packages/malicious/osv/: 609f5b97eb56c6e41c38cbfe56ea0f1296c25ec0
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 4959c8e5c58108f20bcf430d778bef0f02e94757
ossf-package-analysis:
    confident/: confident/20260227/135048-pypi-cicd-ppe-redteam-test02-1.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
