amazon-inspector:
    IN-MAL-: IN-MAL-2025-148779.json
kam193:
    pypi/packages/malicious/osv/: 14297c3ab2e475165b8ab8f8211f767b29d67498
    pypi/packages/pentest/osv/: 14297c3ab2e475165b8ab8f8211f767b29d67498
    pypi/packages/probably_pentest/osv/: 14297c3ab2e475165b8ab8f8211f767b29d67498
ossf-package-analysis:
    confident/: confident/20251130/131207-npm-umap-wasm-2.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
