amazon-inspector:
    IN-MAL-: IN-MAL-2025-149169.json
kam193:
    pypi/packages/malicious/osv/: 35ccd19694fe458f1711c3e7c5711cb00a9f57b1
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: 21ca5d0dc9920f12cb7bd2ce88889dc5a2988496
ossf-package-analysis:
    confident/: confident/20251204/103947-npm-elf-stats-rooftop-stockpile-626-99.0.2.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
