amazon-inspector:
    IN-MAL-: IN-MAL-2025-150307.json
kam193:
    pypi/packages/malicious/osv/: 022ae30bb0a7d4706bc46614816721b2a7944fb9
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: b5f138260fff2230f84df41ac75f146cc0a97761
ossf-package-analysis:
    confident/: confident/20260202/123752-npm-@snazah/davey-2.1.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
