amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: 7ddebe72634c6092d3f7cdbb75751567692aa065
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: b40ab40badc227d4f14998065b4760a13d068de7
ossf-package-analysis:
    confident/: confident/20260205/194102-npm-test-npm-style-1.0.9.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
