amazon-inspector:
    IN-MAL-: IN-MAL-2025-150307.json
kam193:
    pypi/packages/malicious/osv/: 24297d7bf9b4e24dfb76aa5871eab4a3ad2e7535
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 48c78dbd894beafafabaefd1a7016de4da39c076
ossf-package-analysis:
    confident/: confident/20260202/123757-pypi-theanswre-0.2.5.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
