amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: a7f773fb208b80c8d3248f06d5b4b3f3f8bf425a
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: fcd0b014a2ab477c5336ecfad647c6354a0da18f
ossf-package-analysis:
    confident/: confident/20260128/172232-npm-overstock-component-library-v3-4.6.2.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
