amazon-inspector:
    IN-MAL-: IN-MAL-2025-000242.json
ossf-package-analysis:
    confident/: confident/20251031/100040-npm-siren-lament-2.14.822.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
