amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: 7cbc313efce7b5bbfd7ce8cd482d8c8be2d26d55
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 5486c9261b962082045daccb0e27314bedf1e53c
ossf-package-analysis:
    confident/: confident/20260128/172239-npm-overstock-login-layer-3.6.3.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
