amazon-inspector:
    IN-MAL-: IN-MAL-2025-149892.json
kam193:
    pypi/packages/malicious/osv/: a9cb45d924d310d4c3eacfc4a2407a004e41f1a0
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 3b12536cc6aff1b6f6dbf591a69ca888f747e895
ossf-package-analysis:
    confident/: confident/20260112/085856-npm-@testfeii/hallo-word-0.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
