amazon-inspector:
    IN-MAL-: IN-MAL-2025-149197.json
kam193:
    pypi/packages/malicious/osv/: 187f33c06a8864c5d6631589612158405596a26d
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: 9e34d51a5020e10fb1e4a8cc969cbfbec9d86b09
ossf-package-analysis:
    confident/: confident/20251207/093109-npm-react-hook-form-5-90.9.0.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
