amazon-inspector:
    IN-MAL-: IN-MAL-2025-149364.json
kam193:
    pypi/packages/malicious/osv/: 5c82b2571a39ddf7d0e5de00626059ca2322004b
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 18274efc42ff85569015e21fac2b40027370749e
ossf-package-analysis:
    confident/: confident/20251214/050854-npm-@ikarem/telemetry-100.0.5.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
