amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: 09e1ef6152dca3d2e4b478bd86e05b822120fd2c
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: d8995263f22b6bda2f9e5b3f706439563e134047
ossf-package-analysis:
    confident/: confident/20260220/093856-npm-ether-lint-5.9.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
