amazon-inspector:
    IN-MAL-: IN-MAL-2025-149892.json
kam193:
    pypi/packages/malicious/osv/: a03b4706fc83025ce3dac7ab0dd2eff66812a422
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 9d84b7167d78f7fa8a9fd8de69ea3148a2f60643
ossf-package-analysis:
    confident/: confident/20260113/165032-npm-admin1001-4.0.5.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
