amazon-inspector:
    IN-MAL-: IN-MAL-2026-000234.json
kam193:
    pypi/packages/malicious/osv/: 0fa9bf6d7aadd51d6107fe534e3a7c4d4d8d3170
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: e868d3594179d4718f6e996f4a749d1deb8469e0
ossf-package-analysis:
    confident/: confident/20260227/205739-npm-marionette-react-view-9.999.2.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
