amazon-inspector:
    IN-MAL-: IN-MAL-2025-149197.json
kam193:
    pypi/packages/malicious/osv/: 187f33c06a8864c5d6631589612158405596a26d
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: 6e2e28ddfbf31587ff2703390cb0540befe42677
ossf-package-analysis:
    confident/: confident/20251207/223057-npm-paysera-checkout-modal-99.9.9.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
