amazon-inspector:
    IN-MAL-: IN-MAL-2025-000389.json
ossf-package-analysis:
    confident/: confident/20251106/190045-npm-revenuecat-mcp-extension-1.999.9.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
