amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: 3616200b6f564f6ba9562ecc02b503d72072830a
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 7aca717aa3ac596f25bba2e3b40d3c0ebf414480
ossf-package-analysis:
    confident/: confident/20260128/172236-npm-ostk-otel-autoconfig-2.7.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
