amazon-inspector:
    IN-MAL-: IN-MAL-2025-148710.json
ossf-package-analysis:
    confident/: confident/20251130/085524-npm-babel-plugin-standalone-4.1.0.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
