amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: 7734d919d4e4dd37c04fd73dc1b817034e5d1e6c
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 21eb88225f9e1ff2dc7e7b7e500fdfb4f7d8093a
ossf-package-analysis:
    confident/: confident/20260212/195043-npm-envoy1-1.0.17.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
