amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: 9f90d8c18d41d6eccd53421b41e027dbb0be5152
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 0e59804ae1542dc582f9131d65ad4775cdacc5b6
ossf-package-analysis:
    confident/: confident/20260128/194545-npm-epic-asset-uploader-99.9.9.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
