amazon-inspector:
    IN-MAL-: IN-MAL-2025-149615.json
kam193:
    pypi/packages/malicious/osv/: f6664a404a015ac38e6cf91179b070c28bc454a5
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: b86271cc689ed7b864ebb9f2f523fb989a6c997b
ossf-package-analysis:
    confident/: confident/20251221/092118-npm-jest-stable-40.1.10.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
