amazon-inspector:
    IN-MAL-: IN-MAL-2025-149615.json
kam193:
    pypi/packages/malicious/osv/: 650b22c2a97143b83c9fd64203e65b06a2f229b3
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: b86271cc689ed7b864ebb9f2f523fb989a6c997b
ossf-package-analysis:
    confident/: confident/20251221/092118-npm-jest-stable-40.1.10.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
