amazon-inspector:
    IN-MAL-: IN-MAL-2026-000127.json
kam193:
    pypi/packages/malicious/osv/: eacf9bd2f008c2c8bda6b8e0d341861e8363a724
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 9760c24f30ca1073aa18770647174086db50c421
ossf-package-analysis:
    confident/: confident/20260205/193615-npm-test-npm-style-1.0.8.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
