amazon-inspector:
    IN-MAL-: IN-MAL-2025-149615.json
kam193:
    pypi/packages/malicious/osv/: 5a3b7d5887976980e9b1ac027b711bca6684cb96
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 289fd12da3779d19c716702df8eaea7df45c1610
ossf-package-analysis:
    confident/: confident/20251226/140911-npm-bola511-99.99.99.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
