amazon-inspector:
    IN-MAL-: IN-MAL-2025-149615.json
kam193:
    pypi/packages/malicious/osv/: 1a8453d92b969b79e7275af9d1e463948c126062
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 289fd12da3779d19c716702df8eaea7df45c1610
ossf-package-analysis:
    confident/: confident/20251227/025104-npm-backstage-plugin-glean-1.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
