amazon-inspector:
    IN-MAL-: IN-MAL-2025-148710.json
ossf-package-analysis:
    confident/: confident/20251129/182043-npm-eslint-plugin-react-hooks-published-9.1.0.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
