amazon-inspector:
    IN-MAL-: IN-MAL-2025-142388.json
ossf-package-analysis:
    confident/: confident/20251112/111219-npm-karemv1-1.0.4.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
