amazon-inspector:
    IN-MAL-: IN-MAL-2025-005975.json
ossf-package-analysis:
    confident/: confident/20251108/075529-npm-focusync-custom-controls-99.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
