amazon-inspector:
    IN-MAL-: IN-MAL-2026-000234.json
kam193:
    pypi/packages/malicious/osv/: 157eb0fb0958ccdca39a041bb31d1bdcb2bf240b
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: e868d3594179d4718f6e996f4a749d1deb8469e0
ossf-package-analysis:
    confident/: confident/20260227/135048-pypi-cicd-ppe-redteam-test02-1.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
