amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: 1137dd67cb017e83ab75fc91f2c88178d63883c4
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 32056007e27b040f085bbe966349b9628a4d8996
ossf-package-analysis:
    confident/: confident/20260206/110703-npm-ethers-lint-5.8.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
