amazon-inspector:
    IN-MAL-: IN-MAL-2025-000664.json
ossf-package-analysis:
    confident/: confident/20251107/185536-npm-globby-legacy-20.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
