amazon-inspector:
    IN-MAL-: IN-MAL-2025-149364.json
kam193:
    pypi/packages/malicious/osv/: 59a3d05a8c528a9aa2da488565c07a4ad2827d4c
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 43d4ede7946edae867304b34218023c35384bd05
ossf-package-analysis:
    confident/: confident/20251219/213230-npm-jest-stable-40.1.9.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
