amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: e137907f6b21ae18d812831de80767fe1796d5d0
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: eda73c194f9cf206ce0be935687496cdbb940b72
ossf-package-analysis:
    confident/: confident/20260211/081550-npm-npm_cimetadata-0.0.2.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
