amazon-inspector:
    IN-MAL-: IN-MAL-2025-149615.json
kam193:
    pypi/packages/malicious/osv/: dadf69038d0e598973640f08a48fe89a6952a0f3
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: cd79bbe3e3086e9e01c820cccfb5ea0906a8d2c2
ossf-package-analysis:
    confident/: confident/20251221/092118-npm-jest-stable-40.1.10.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
