amazon-inspector:
    IN-MAL-: IN-MAL-2026-000234.json
kam193:
    pypi/packages/malicious/osv/: 51dfaa5facc53602eb47dcf0e100a3369f845fad
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 5f19d075c52cfa0972cb7f60610aa180534b7fa5
ossf-package-analysis:
    confident/: confident/20260223/133247-npm-vl-ui-button-10.1.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
