amazon-inspector:
    IN-MAL-: IN-MAL-2025-150037.json
kam193:
    pypi/packages/malicious/osv/: c86e2d4fd31e95839e74e1eb2f52bffda62f8691
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: e432e3ea614ed06235915cdbb88a81301f864b63
ossf-package-analysis:
    confident/: confident/20260116/172037-npm-admin10001-1.0.25.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
