amazon-inspector:
    IN-MAL-: IN-MAL-2025-148779.json
kam193:
    pypi/packages/malicious/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
    pypi/packages/probably_pentest/osv/: 27cbe31837ebfb9ccc169b6c60ebc77b8545845e
ossf-package-analysis:
    confident/: confident/20251201/212127-npm-browser-client-neptune-99.99.92.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
