amazon-inspector:
    IN-MAL-: IN-MAL-2025-150191.json
kam193:
    pypi/packages/malicious/osv/: 626a4a9d2668e7cf91f9d7cb9f7bb27b6a78d90f
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: e46a0c5acb19e608afe38dd482f68551786c3690
ossf-package-analysis:
    confident/: confident/20260130/153112-npm-euskalplantxa-5.8.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
