amazon-inspector:
    IN-MAL-: IN-MAL-2025-150037.json
kam193:
    pypi/packages/malicious/osv/: 28fa1a637014f841271b07c5a37c3028f2fb8847
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 5b9831ad8622f96270c38e41db314115930b8bb5
ossf-package-analysis:
    confident/: confident/20260122/175100-npm-uuu8lgd-1.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
