amazon-inspector:
    IN-MAL-: IN-MAL-2025-147532.json
ossf-package-analysis:
    confident/: confident/20251116/194657-npm-com.mixpanel.unity-5.5.3.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
