amazon-inspector:
    IN-MAL-: IN-MAL-2025-150307.json
kam193:
    pypi/packages/malicious/osv/: 6c9fdb0c6b519082d4484e41e43c0fee7bc2f2be
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 638bcd1641f7c4c566ae700f2eb70ac5d11d0bc6
ossf-package-analysis:
    confident/: confident/20260203/154103-npm-@x-clients/features-3.1.10.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
