amazon-inspector:
    IN-MAL-: IN-MAL-2025-149777.json
kam193:
    pypi/packages/malicious/osv/: 6341abc4255d345fcbe101d6494c13ac30beb70f
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 6a2786f0ddb5020efeca965206d6225583dcf691
ossf-package-analysis:
    confident/: confident/20260105/005620-npm-spire.officejs-document-1.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
