amazon-inspector:
    IN-MAL-: IN-MAL-2025-150037.json
kam193:
    pypi/packages/malicious/osv/: b021733493ec8f65c5138d6590ee73d6a49120e8
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 24b68696d1552b46ce75d85b7c57f46fc1c6beb6
ossf-package-analysis:
    confident/: confident/20260117/152542-npm-admin10001-1.0.172.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
