amazon-inspector:
    IN-MAL-: IN-MAL-2025-149777.json
kam193:
    pypi/packages/malicious/osv/: 5b315c7ad7db782203a4c3e1c8b5c4bf5fe70651
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 3bcc0f0b7fc0398daa8632fa940bd3ed781966ce
ossf-package-analysis:
    confident/: confident/20251229/074542-npm-crypto-trade-analyzer-2.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
