amazon-inspector:
    IN-MAL-: IN-MAL-2025-000389.json
ossf-package-analysis:
    confident/: confident/20251105/151331-npm-capes-template-angular-10.0.7.json
reversing-labs:
    RLMA-: RLMA-2025-05558.json
    RLUA-: RLUA-2025-05510.json
