amazon-inspector:
    IN-MAL-: IN-MAL-2025-149892.json
kam193:
    pypi/packages/malicious/osv/: ff3cbed2341abc090f1a3112eeac651ad38b7852
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 15a74b1b9915704c790a0a9b643cfbca9c22ece4
ossf-package-analysis:
    confident/: confident/20260114/132247-npm-admin1001-4.3.35.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
