amazon-inspector:
    IN-MAL-: IN-MAL-2026-000234.json
kam193:
    pypi/packages/malicious/osv/: 84019a0d564f0381d70baccbf8d2e67da1314f41
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: af9d6970ad9b1bd40a6b84ebc8596af817f220a9
ossf-package-analysis:
    confident/: confident/20260223/133244-npm-vl-ui-body-10.1.1.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
