amazon-inspector:
    IN-MAL-: IN-MAL-2025-149262.json
kam193:
    pypi/packages/malicious/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
ossf-package-analysis:
    confident/: confident/20251210/165818-npm-@cheqplease/structured-logger-9.3.2.json
reversing-labs:
    RLMA-: RLMA-2025-05986.json
    RLUA-: RLUA-2025-05995.json
