amazon-inspector:
    IN-MAL-: IN-MAL-2025-150037.json
kam193:
    pypi/packages/malicious/osv/: b8e4ffd6840b4b90ba4cd08aea34cc6047d8aaf9
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 24b68696d1552b46ce75d85b7c57f46fc1c6beb6
ossf-package-analysis:
    confident/: confident/20260117/153045-npm-admin10001-1.0.173.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
