amazon-inspector:
    IN-MAL-: IN-MAL-2026-000130.json
kam193:
    pypi/packages/malicious/osv/: ffae695f86869d9d383a8fecbf048c309655fc57
    pypi/packages/pentest/osv/: 0d65fa30569acb74a4cd2f6968297f9cf794b510
    pypi/packages/probably_pentest/osv/: 7f619fa8e8ac063aaf39339a6901e0848242e169
ossf-package-analysis:
    confident/: confident/20260212/204054-npm-@depro0x/despicable-me-8.0.0.json
reversing-labs:
    RLMA-: RLMA-2025-06626.json
    RLUA-: RLUA-2025-06573.json
