name: Assign OSV IDs

on:
  push:
    branches:
    - main
  schedule:
  - cron: '7 * * * *' # Once an hour
  workflow_dispatch:

permissions: read-all

jobs:
  assign-ids:
    name: Assign IDs
    continue-on-error: false
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
    - uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3
    - uses: actions/setup-go@fac708d6674e30b6ba41289acaab6d4b75aa0753 # v4.0.1
      with:
        go-version: "1.20"

    - name: Preprocess reports
      run: make preprocess

    - name: Assign IDs
      run: |
        go install github.com/google/osv/vulnfeeds/cmd/ids@latest
        ids -dir=./malicious -prefix MAL -format json
      env:
        GONOPROXY: github.com/google/osv

    - name: Prepare commit
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
    - name: Commit report changes
      run: git diff --cached --quiet || git commit -m 'Assign IDs'
    - name: Push commit
      run: git push
