name: Assign OSV IDs

on:
  push:
    branches:
    - main
  schedule:
  - cron: '7 * * * *' # Once an hour
  workflow_dispatch:

permissions: read-all

jobs:
  assign-ids:
    name: Assign IDs
    continue-on-error: false
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: write

    steps:
    - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      with:
        token: ${{ secrets.GH_TOKEN }}
    - uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
      with:
        go-version: "1.21"

    - name: Preprocess reports
      run: make preprocess

    - name: Assign IDs
      run: |
        go install github.com/google/osv/vulnfeeds/cmd/ids@latest
        ids -dir=./osv/malicious -prefix MAL -format json
      env:
        GONOPROXY: github.com/google/osv

    - name: Prepare commit
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
    - name: Commit report changes
      run: git diff --cached --quiet || git commit -m 'Assign IDs'
    - name: Push commit
      run: git push
